# name: Example Workflow

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   schedule:
#     - cron: '0 0 * * *'
#   workflow_dispatch:

# jobs:
#   echo:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Echo message
#         run: echo "Hello, world!"


#error: The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
# The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3. 
##############################

name: Example Workflow

on:
 # push:
 # pull_request:
 # schedule:
 #   - cron: '0 0 * * *'    #note cron does not take 6 elements.  Only takes 5 elements
                            #runs every day at 12am
  workflow_dispatch:       # trigger the workflow from the UI


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."