name: 04 - Using Actions

# on: push

jobs:
  build:
    runs-on: workflow_dispatch
    defaults: 
      run:
        working-directory: ./04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
  

    #0. Checkout the code form the repository  (Workflows need to be defined in the same repository)
    #1. Isntall dependencies of our react app
    #2. Execute automated tests


